GET http://127.0.0.1:3000/api/tokens/Terry-404

###
PUT http://127.0.0.1:3000/api/tokens/
Content-Type: application/json

{
    "token": "Terry-404",
    "password": "Terry-404",
    "task": "Create the repo",
    "state": true
}

###

DELETE http://127.0.0.1:3000/api/tokens/
Content-Type: application/json

{
    "token": "Terry-404",
    "password": "12345678",
    "task": "Create the repo"
}

###
POST http://127.0.0.1:3000/api/tokens/
Content-Type: application/json

{
    "action": "task",
    "token": "Terry-404",
    "password": "Terry-404",
    "task": "Create new task"
}